In [438]:
import pandas as pd

In [439]:
games_raw = pd.read_csv('games_stats.csv')
games_raw

,Unnamed: 0,Team,Match Up,Game Date,Season,W/L,MIN,PTS,FGM,FGA,...,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,PF,+/-
0,0,CHI,CHI @ MIN,04/10/2022,NaN,W,240,124,44,83,...,78.8,16,32,48,22,9,3,23,22,4
1,1,MIN,MIN vs. CHI,04/10/2022,NaN,L,240,120,46,91,...,77.3,9,23,32,30,7,9,13,23,-4
2,2,PHI,PHI vs. DET,04/10/2022,NaN,W,240,118,46,88,...,91.3,10,32,42,25,13,6,11,23,12
3,3,DET,DET @ PHI,04/10/2022,NaN,L,240,106,38,83,...,65.5,15,27,42,26,4,4,20,16,-12
4,4,BOS,BOS @ MEM,04/10/2022,NaN,W,240,139,54,99,...,100.0,14,42,56,34,5,2,15,20,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6733,2113,BOS,BOS @ PHI,10/23/2019,NaN,L,240,93,33,90,...,58.8,10,31,41,18,4,2,11,29,-14
6734,2114,NOP,NOP @ TOR,10/22/2019,NaN,L,265,122,43,102,...,85.0,16,37,53,30,4,9,19,34,-8
6735,2115,TOR,TOR vs. NOP,10/22/2019,NaN,W,265,130,42,103,...,84.2,16,41,57,23,7,3,17,24,8
6736,2116,LAC,LAC vs. LAL,10/22/2019,NaN,W,240,112,42,81,...,70.8,11,34,45,24,8,5,14,25,10
6737,2117,LAL,LAL @ LAC,10/22/2019,NaN,L,240,102,37,85,...,71.4,9,32,41,20,4,7,15,24,-10

In [440]:
games_raw.describe()

,Unnamed: 0,Season,MIN,PTS,FGM,FGA,FG%,3PM,3PA,3P%,...,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,PF,+/-
count,6738.000000,0.0,6738.000000,6738.000000,6738.000000,6738.000000,6738.000000,6738.000000,6738.000000,6738.000000,...,6738.000000,6738.000000,6738.000000,6738.000000,6738.000000,6738.000000,6738.000000,6738.000000,6738.000000,6738.000000
mean,1127.662956,NaN,241.513802,111.460374,40.887504,88.426981,46.331077,12.449837,34.670377,35.845666,...,77.504779,10.091125,34.430988,44.522113,24.615910,7.617691,4.822796,14.031315,19.884090,0.000000
std,657.540400,NaN,6.640308,12.541467,5.188830,6.874180,5.487810,3.855016,6.884390,8.433099,...,10.230788,3.645043,5.410703,6.556762,4.961481,2.879995,2.433208,3.941090,4.189664,14.986491
min,0.000000,NaN,240.000000,73.000000,21.000000,63.000000,26.900000,2.000000,10.000000,7.700000,...,30.800000,0.000000,16.000000,24.000000,8.000000,0.000000,0.000000,1.000000,6.000000,-73.000000
25%,561.000000,NaN,240.000000,103.000000,37.000000,84.000000,42.500000,10.000000,30.000000,30.200000,...,71.000000,8.000000,31.000000,40.000000,21.000000,6.000000,3.000000,11.000000,17.000000,-10.000000
50%,1122.500000,NaN,240.000000,111.000000,41.000000,88.000000,46.300000,12.000000,34.000000,35.700000,...,77.800000,10.000000,34.000000,44.000000,24.000000,7.000000,5.000000,14.000000,20.000000,0.000000
75%,1684.000000,NaN,240.000000,120.000000,44.000000,93.000000,50.000000,15.000000,39.000000,41.500000,...,84.600000,12.000000,38.000000,49.000000,28.000000,9.000000,6.000000,17.000000,23.000000,10.000000
max,2459.000000,NaN,315.000000,159.000000,63.000000,120.000000,68.700000,29.000000,63.000000,68.000000,...,100.000000,26.000000,55.000000,70.000000,50.000000,22.000000,20.000000,30.000000,37.000000,73.000000

In [441]:
games_raw = games_raw.drop(columns = ['Unnamed: 0', 'Season', '+/-', 'PF', ])
games_raw

,Team,Match Up,Game Date,W/L,MIN,PTS,FGM,FGA,FG%,3PM,...,FTM,FTA,FT%,OREB,DREB,REB,AST,STL,BLK,TOV
0,CHI,CHI @ MIN,04/10/2022,W,240,124,44,83,53.0,10,...,26,33,78.8,16,32,48,22,9,3,23
1,MIN,MIN vs. CHI,04/10/2022,L,240,120,46,91,50.5,11,...,17,22,77.3,9,23,32,30,7,9,13
2,PHI,PHI vs. DET,04/10/2022,W,240,118,46,88,52.3,5,...,21,23,91.3,10,32,42,25,13,6,11
3,DET,DET @ PHI,04/10/2022,L,240,106,38,83,45.8,11,...,19,29,65.5,15,27,42,26,4,4,20
4,BOS,BOS @ MEM,04/10/2022,W,240,139,54,99,54.5,18,...,13,13,100.0,14,42,56,34,5,2,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6733,BOS,BOS @ PHI,10/23/2019,L,240,93,33,90,36.7,7,...,20,34,58.8,10,31,41,18,4,2,11
6734,NOP,NOP @ TOR,10/22/2019,L,265,122,43,102,42.2,19,...,17,20,85.0,16,37,53,30,4,9,19
6735,TOR,TOR vs. NOP,10/22/2019,W,265,130,42,103,40.8,14,...,32,38,84.2,16,41,57,23,7,3,17
6736,LAC,LAC vs. LAL,10/22/2019,W,240,112,42,81,51.9,11,...,17,24,70.8,11,34,45,24,8,5,14
6737,LAL,LAL @ LAC,10/22/2019,L,240,102,37,85,43.5,13,...,15,21,71.4,9,32,41,20,4,7,15

In [442]:
games_raw.columns

Index(['Team', 'Match Up', 'Game Date', 'W/L', 'MIN', 'PTS', 'FGM', 'FGA',
       'FG%', '3PM', '3PA', '3P%', 'FTM', 'FTA', 'FT%', 'OREB', 'DREB', 'REB',
       'AST', 'STL', 'BLK', 'TOV'],
      dtype='object')

Separate home and away games

In [443]:
away_teams = games_raw.loc[games_raw['Match\xa0Up'].str.contains('@')]
away_teams = away_teams.reset_index(drop=True)
home_teams = games_raw.loc[games_raw['Match\xa0Up'].str.contains('vs.')]
home_teams = home_teams.reset_index(drop=True)
home_teams.rename(columns= lambda x: 'Home ' + x, inplace=True)
away_teams.rename(columns= lambda x: 'Away ' + x, inplace=True)
list(away_teams.columns)

['Away Team',
 'Away Match\xa0Up',
 'Away Game\xa0Date',
 'Away W/L',
 'Away MIN',
 'Away PTS',
 'Away FGM',
 'Away FGA',
 'Away FG%',
 'Away 3PM',
 'Away 3PA',
 'Away 3P%',
 'Away FTM',
 'Away FTA',
 'Away FT%',
 'Away OREB',
 'Away DREB',
 'Away REB',
 'Away AST',
 'Away STL',
 'Away BLK',
 'Away TOV']

merge away and home dataframes

In [444]:
merge_games = home_teams.merge(away_teams, how='outer', left_index=True, right_index=True)

In [445]:
list(merge_games.columns)
# merge_games = merge_games.drop(columns=['Away Match\xa0Up', 'Away MIN',])
merge_games['Home Wins'] = merge_games.apply(lambda x: 1 if x['Home W/L'] == "W" else 0, axis=1)
merge_games = merge_games.drop(columns=['Away Match\xa0Up', 'Away MIN', 'Home W/L', 'Away W/L'])
match_up = merge_games.pop('Home Match\xa0Up')
game_date = merge_games.pop('Home Game\xa0Date')
merge_games.insert(0, 'Date', game_date)
merge_games.insert(1, 'Game', match_up)
cleaned_games = merge_games
cleaned_games

,Date,Game,Home Team,Home MIN,Home PTS,Home FGM,Home FGA,Home FG%,Home 3PM,Home 3PA,...,Away FTA,Away FT%,Away OREB,Away DREB,Away REB,Away AST,Away STL,Away BLK,Away TOV,Home Wins
0,04/10/2022,MIN vs. CHI,MIN,240,120,46,91,50.5,11,31,...,33,78.8,16,32,48,22,9,3,23,0
1,04/10/2022,PHI vs. DET,PHI,240,118,46,88,52.3,5,25,...,29,65.5,15,27,42,26,4,4,20,1
2,04/10/2022,MEM vs. BOS,MEM,240,110,39,102,38.2,15,47,...,13,100.0,14,42,56,34,5,2,15,0
3,04/10/2022,DEN vs. LAL,DEN,265,141,49,100,49.0,15,47,...,47,89.4,13,37,50,26,4,6,13,0
4,04/10/2022,ORL vs. MIA,ORL,240,125,45,91,49.5,23,58,...,16,75.0,10,37,47,20,5,4,10,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3364,10/23/2019,PHX vs. SAC,PHX,240,124,49,98,50.0,11,33,...,26,65.4,12,35,47,17,5,5,27,1
3365,10/23/2019,SAS vs. NYK,SAS,240,120,42,83,50.6,7,21,...,18,72.2,5,34,39,24,16,1,14,1
3366,10/23/2019,PHI vs. BOS,PHI,240,107,37,85,43.5,7,29,...,34,58.8,10,31,41,18,4,2,11,1
3367,10/22/2019,TOR vs. NOP,TOR,265,130,42,103,40.8,14,40,...,20,85.0,16,37,53,30,4,9,19,1
3368,10/22/2019,LAC vs. LAL,LAC,240,112,42,81,51.9,11,31,...,21,71.4,9,32,41,20,4,7,15,1

In [446]:
cleaned_games.to_csv('cleaned_games_stats.csv', mode='a', header=False)